- name: Configure OSPF Unnumbered Switches
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

  - name: Initial Switch Management VRF setup
    nclu:
      commit: true
      description: "Initial Management VRF setup"
      commands:
        - add interface eth0 vrf mgmt
        - add hostname "{{ inventory_hostname }}"

  - name: Deploy Interfaces
    nclu:
      commit: true
      description: "Deploy Interfaces"
      template: |
         add interface "{{ item }}"
    with_items:
      - "{{ node[inventory_hostname].ports }}"
    when: node[inventory_hostname].ports is defined

  - name: Deploy OSPF Unnumbered configuration
    nclu:
        commit: true
        description: "Deploy OSPF Unnumbered configuration"
        commands:
            - add loopback lo ip address {{ node[inventory_hostname].routing.lo }}
            - add ospf router-id {{ node[inventory_hostname].routing.lo | regex_replace('/32') }}
            - add ospf network {{ node[inventory_hostname].routing.lo }} area {{ node[inventory_hostname].routing.ospf.area }}

  - name: Deploy OSPF Unnumbered Interfaces
    nclu:
        commit: true
        description: "Deploy OSPF Unnumbered Interfaces"
        template: |
           add interface {{ item }} ospf network point-to-point
           add interface {{ item }} ip address {{ node[inventory_hostname].routing.lo }}
    with_items:
      - "{{ node[inventory_hostname].routing.ospf.neighbors }}"
    when: node[inventory_hostname].routing.ospf.neighbors is defined

  - name: Reload Interfaces
    command: ifreload -a
