- name: Simple Debug Script
  hosts: all
  gather_facts: yes

  tasks:
#   - debug:
#       msg: "{{ node[inventory_hostname].ports }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.ospf.neighbors }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.lo | regex_replace('/32')}}"

   - debug:
       msg: "add interface {{ item }} ospf network point-to-point"
     with_items: "{{ node[inventory_hostname].routing.ospf.neighbors }}"
